resolve conflict between mockito, hamcrest, awaitility
We should depend on mockito-core rather than mockito-all as the latter
repackages hamcrest classes.

This fixes an error that is thrown from within awaitility like:

> java.lang.NoSuchMethodError: org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V