agent: supervisor error handling
Closing the docker request reply stream can
apparently throw an NPE.

testAgentRestart(com.spotify.helios.SystemTest)  Time elapsed: 269.136 sec  <<< ERROR!
java.lang.IllegalStateException: Expected the service to be TERMINATED, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:334)
	at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:303)
	at com.google.common.util.concurrent.AbstractIdleService.awaitTerminated(AbstractIdleService.java:191)
	at com.spotify.helios.SystemTest.teardown(SystemTest.java:93)
Caused by: java.lang.NullPointerException: null
	at org.apache.http.conn.BasicManagedEntity.streamClosed(BasicManagedEntity.java:165)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:237)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:186)
	at java.io.BufferedInputStream.close(BufferedInputStream.java:472)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler$HttpClientResponseInputStream.close(ApacheHttpClient4Handler.java:325)
	at com.spotify.helios.agent.Supervisor$RunnerImpl.stop(Supervisor.java:349)
	at com.spotify.helios.agent.Supervisor.close(Supervisor.java:122)
	at com.spotify.helios.agent.Agent.close(Agent.java:75)
	at com.spotify.helios.agent.AgentService.stop(AgentService.java:115)
	at com.spotify.helios.agent.AgentMain.shutDown(AgentMain.java:41)
	at com.google.common.util.concurrent.AbstractIdleService$2$2.run(AbstractIdleService.java:69)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.lang.Thread.run(Thread.java:724)