shade/relocate dns dependencies of helios-client
For anyone adding recent version of `helios-testing` to their projects
*and* using `com.spotify:dns:2.x`, there is a dependency conflict
waiting to happen as there were changes in 3.x that are backwards
incompatible with 2.x.

This will relocate the DNS-related classes in `helios-client` (where the
dependency in `helios-testing` comes from) to prevent these headaches
for users.

Someone attempting to use the problematic versions of helios-testing
with version 2.x of `com.spotify:dns` will get errors like:

```
java.lang.NoSuchMethodError: com.spotify.dns.DnsSrvResolvers$DnsSrvResolverBuilder.metered(Z)Lcom/spotify/dns/DnsSrvResolvers$DnsSrvResolverBuilder;
```